name: Generating GALDEF files

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Generating GALDEF files
      run: |
        python HydHdz/CosmicRays/GALDEFGEN/GenGalprop.py
